Repository OpenSlides/OpenSlides, pull requests merged in 2018-09, with the labels that each got.

#3866 multi-value-selector as shared component
  client/package-lock.json
  client/package.json
  client/src/app/shared/components/search-value-selector/search-value-selector.component.html
  client/src/app/shared/components/search-value-selector/search-value-selector.component.scss
  client/src/app/shared/components/search-value-selector/search-value-selector.component.spec.ts
  client/src/app/shared/components/search-value-selector/search-value-selector.component.ts
  client/src/app/shared/components/search-value-selector/search-value-selector.interfaces.ts
  client/src/app/shared/models/agenda/item.ts
  client/src/app/shared/models/assignments/assignment.ts
  client/src/app/shared/models/base.model.ts
  client/src/app/shared/models/core/chat-message.ts
  client/src/app/shared/models/core/config.ts
  client/src/app/shared/models/core/countdown.ts
  client/src/app/shared/models/core/projector-message.ts
  client/src/app/shared/models/core/projector.ts
  client/src/app/shared/models/core/tag.ts
  client/src/app/shared/models/mediafiles/mediafile.ts
  client/src/app/shared/models/motions/category.ts
  client/src/app/shared/models/motions/motion-block.ts
  client/src/app/shared/models/motions/motion-change-reco.ts
  client/src/app/shared/models/motions/motion-comment-section.ts
  client/src/app/shared/models/motions/motion-submitter.ts
  client/src/app/shared/models/motions/motion.ts
  client/src/app/shared/models/motions/workflow.ts
  client/src/app/shared/models/topics/topic.ts
  client/src/app/shared/models/users/group.ts
  client/src/app/shared/models/users/personal-note.ts
  client/src/app/shared/models/users/user.ts
  client/src/app/shared/shared.module.ts
  client/src/app/site/base-repository.ts
  client/src/app/site/motions/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/components/motion-detail/motion-detail.component.ts
  client/src/app/site/motions/services/motion-repository.service.ts
  client/src/app/site/start/start.component.ts
  client/src/assets/i18n/de.json
  client/src/assets/i18n/en.json
  client/src/assets/i18n/fr.json
Labels: client, html/css, js, needs review

#3860 Moved the collection of config variables before the generation of ang…
  client/src/app/app.component.ts
  client/src/app/site/settings/settings-list/settings-list.component.ts
  openslides/__main__.py
  openslides/agenda/apps.py
  openslides/assignments/apps.py
  openslides/core/apps.py
  openslides/core/config.py
  openslides/motions/apps.py
  openslides/users/apps.py
  requirements/development.txt
Labels: high, server

#3889 Fix image plugin
  openslides/mediafiles/static/js/mediafiles/image-plugin.js
Labels: bug
