Repository OpenSlides/OpenSlides, pull requests merged in 2018-03, with the labels that each got.

#3616 Adapt motion csv import example file (Fix #3613).
  openslides/motions/static/js/motions/csv.js
Labels: easy

#3631 Moved image sources to the virtual filesystem
  openslides/core/static/js/core/pdf.js
  openslides/motions/static/js/motions/pdf.js
  openslides/topics/static/js/topics/site.js
Labels: needs review

#3630 Fixed delection of logos and fonts. Closes #3606
  openslides/core/static/js/core/base.js
Labels: easy

#3634 Added event name to web interface header.
  openslides/core/static/templates/index.html
Labels: easy, needs review

#3626 Change recommendations for motion titles
  CHANGELOG
  openslides/motions/serializers.py
  openslides/motions/static/css/motions/_change-recommendation-overview.scss
  openslides/motions/static/css/motions/_site.scss
  openslides/motions/static/js/motions/base.js
  openslides/motions/static/js/motions/docx.js
  openslides/motions/static/js/motions/motion-services.js
  openslides/motions/static/js/motions/pdf.js
  openslides/motions/static/js/motions/site.js
  openslides/motions/static/templates/motions/motion-detail.html
  openslides/motions/static/templates/motions/motion-detail/change-summary.html
  openslides/motions/static/templates/motions/motion-detail/toolbar.html
  openslides/motions/static/templates/motions/motion-detail/view-diff.html
Labels: needs review

#3638 Disable the agenda hierachy just for searchning, not for filtering
  openslides/agenda/static/js/agenda/site.js
  openslides/agenda/static/templates/agenda/item-list.html
Labels: needs review

#3639 Some minor CSS improvements.
  openslides/agenda/static/templates/agenda/item-list.html
  openslides/core/static/css/core/_projector.scss
  openslides/motions/static/css/motions/_projector.scss
Labels: easy, needs review

#3642 Bugfix: Title change recommendations on the projector
  openslides/motions/static/css/motions/_projector.scss
  openslides/motions/static/js/motions/projector.js
  openslides/motions/static/templates/motions/slide_motion.html
Labels: needs review

#3648 Pdf fixes
  openslides/agenda/static/js/agenda/pdf.js
  openslides/assignments/static/js/assignments/pdf.js
  openslides/core/static/js/core/pdf.js
  openslides/users/static/js/users/pdf.js
Labels: needs review

#3651 Layout improvements for agenda and motions
  openslides/agenda/static/css/agenda/_projector.scss
  openslides/agenda/static/templates/agenda/slide-item-list.html
  openslides/core/static/css/_helper.scss
  openslides/motions/static/templates/motions/motion-detail.html
  openslides/topics/static/templates/topics/slide_topic.html
  openslides/topics/static/templates/topics/topic-detail.html
Labels: needs review

#3652 Improved error handling of re-numbering motions of a category.
  openslides/motions/views.py
Labels: needs review

#3649 Fixed Nginx settings
  DEVELOPMENT.rst
Labels: easy, needs review

#3646 Go to original view after deleting the Title CR...
  openslides/motions/static/js/motions/motion-services.js
Labels: needs review

#3644 OL Offsets - fixes #3643
  CHANGELOG
  openslides/motions/static/js/motions/diff.js
  tests/karma/motions/diff.service.test.js
Labels: needs review

#3655 Fix group filtering in users list view
  openslides/users/static/templates/users/user-list.html
Labels: needs review

#3660 Fix for creating assignment ballot pdf.
  openslides/assignments/static/js/assignments/pdf.js
Labels: needs review

#3661 Fixing translations (fixes #3607, fixes #3604).
  openslides/agenda/static/js/agenda/csv.js
  openslides/motions/static/js/motions/csv.js
  openslides/motions/static/js/motions/docx.js
  openslides/topics/static/js/topics/csv.js
  openslides/users/static/js/users/csv.js
  openslides/users/static/js/users/site.js
  openslides/users/static/templates/users/group-edit.html
  openslides/users/static/templates/users/group-list.html
Labels: easy, needs review

#3657 Add firstLine to cache definition - fixes #3656
  CHANGELOG
  openslides/motions/static/js/motions/linenumbering.js
Labels: needs review

#3659 Autoupdates for all children if the item type has changed (fixes #3636).
  CHANGELOG
  openslides/agenda/views.py
Labels: needs review
