Repository OpenSlides/OpenSlides, pull requests merged in 2020-08, with the labels that each got.

#5493 Fix syntax of models.txt
  docs/models.txt
Labels: OpenSlides4

#5497 Cleaner pdf getUnifiedChanges solution
  client/src/app/site/motions/services/motion-pdf.service.ts
Labels: high, motions, pdf

#5500 Add "create user" to more search value selectors
  client/src/app/core/repositories/assignments/assignment-repository.service.ts
  client/src/app/core/repositories/users/user-repository.service.ts
  client/src/app/shared/components/sorting-list/sorting-list.component.html
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: feature

#5498 Update jitsi-meet external api
  client/src/app/shared/components/jitsi/jitsi.component.ts
  client/src/assets/jitsi/external_api.js
Labels: dependencies

#5495 Ping redis connection when popped from pool
  .gitignore
  openslides/utils/redis_connection_pool.py
Labels: high

#5505 Download mutliple files as zip
  client/package.json
  client/src/app/core/core-services/http.service.ts
  client/src/app/core/pdf-services/pdf-document.service.ts
  client/src/app/core/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.html
  client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.ts
Labels: feature

#5502 Replace meeting room keyframe animation
  client/src/app/shared/components/jitsi/jitsi.component.html
  client/src/app/shared/components/jitsi/jitsi.component.scss
  client/src/app/shared/components/jitsi/jitsi.component.ts
Labels: bug

#5506 Update TinyMCE and TinyMCE angular
  client/angular.json
  client/package.json
  client/src/app/shared/shared.module.ts
Labels: client, high

#5509 Add https-info and enhance work-in-submodules doc
  DEVELOPMENT.md
Labels: OpenSlides4, documentation

#5499 Add calculated fields
  docs/example-data.json
  docs/models.txt
Labels: OpenSlides4

#5518 Add reverse models for generic relations in models.txt (closes #5337)
  docs/models.txt
Labels: OpenSlides4

#5524 Update models.txt
  docs/example-data.json
  docs/models.txt
Labels: OpenSlides4

#5522 Fix selector with in submitter component
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/site/motions/modules/motion-detail/components/manage-submitters/manage-submitters.component.html
  client/src/app/site/motions/modules/motion-detail/components/manage-submitters/manage-submitters.component.ts
Labels: bug, client

#5516 Hide motion preamble in final state
  client/src/app/site/motions/models/view-motion.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail-diff/motion-detail-diff.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-detail-diff/motion-detail-diff.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
  client/src/app/site/motions/services/motion-pdf.service.ts
Labels: client, feature

#5529 Add "supporter" to motion export dialog
  client/src/app/site/motions/motions.constants.ts
  client/src/app/site/motions/services/motion-pdf.service.ts
Labels: client, feature
