Repository OpenSlides/OpenSlides, pull requests merged in 2020-01, with the labels that each got.

#5167 Added optional argument '--email' for createopenslidesuser command.
  openslides/users/management/commands/createopenslidesuser.py
Labels: server

#5172 Fix group creation
  openslides/users/serializers.py
  tests/integration/users/test_viewset.py
Labels: bug, high, server

#5175 Polls for motions and assignments
  client/src/app/shared/components/banner/banner.component.html
  client/src/app/shared/components/banner/banner.component.scss
  client/src/app/shared/components/banner/banner.component.scss-theme.scss
  client/src/app/shared/components/charts/charts.component.html
  client/src/app/shared/components/charts/charts.component.ts
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/assignments/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/assignments/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/assignments/components/assignment-poll-vote/assignment-poll-vote.component.html
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.html
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.ts
  client/src/app/site/assignments/models/view-assignment-poll.ts
  client/src/app/site/motions/models/view-motion-poll.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.ts
  client/src/app/site/motions/modules/motion-poll/motion-poll-dialog/motion-poll-dialog.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-dialog/motion-poll-dialog.component.ts
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.ts
  client/src/app/site/motions/services/motion-poll.service.ts
  client/src/app/site/polls/components/base-poll-detail.component.ts
  client/src/app/site/polls/components/base-poll.component.ts
  client/src/app/site/polls/components/poll-form/poll-form.component.html
  client/src/app/site/polls/components/poll-form/poll-form.component.ts
  client/src/app/site/polls/models/view-base-poll.ts
  client/src/styles.scss
Labels: development

#5173 Use amendmend wizzard for amendments
  client/src/app/core/repositories/motions/motion-repository.service.ts
  client/src/app/site/motions/modules/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.html
  client/src/app/site/motions/modules/motion-detail/components/amendment-create-wizard/amendment-create-wizard.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: client, motions

#5188 Use defineProperties for array functions
  client/src/app/app.component.ts
  client/src/app/site/polls/components/poll-form/poll-form.component.ts
Labels: development

#5187 Update ngrid, redefine prototypes of datatypes
  client/package.json
  client/src/app/app.component.ts
  client/src/app/shared/components/list-view-table/list-view-table.component.ts
Labels: bug, clean up, client, dependencies

#5195 Fix flat map
  client/src/app/app.component.ts
Labels: bug, high

#5192 Show final state in Motion PDF toc
  client/src/app/core/translate/marked-translations.ts
  client/src/app/site/motions/services/motion-pdf-catalog.service.ts
  openslides/motions/config_variables.py
Labels: feature, motions, pdf

#5189 More voting UI improvements
  client/src/app/core/pdf-services/base-poll-pdf-service.ts
  client/src/app/shared/models/poll/base-poll.ts
  client/src/app/shared/pipes/parse-poll-number.pipe.spec.ts
  client/src/app/shared/pipes/parse-poll-number.pipe.ts
  client/src/app/shared/pipes/reverse.pipe.spec.ts
  client/src/app/shared/pipes/reverse.pipe.ts
  client/src/app/shared/shared.module.ts
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.html
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll-dialog/motion-poll-dialog.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-dialog/motion-poll-dialog.component.ts
  client/src/app/site/motions/modules/motion-poll/motion-poll-vote/motion-poll-vote.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-vote/motion-poll-vote.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.ts
  client/src/app/site/motions/services/motion-poll-pdf.service.ts
  client/src/app/site/polls/components/base-poll-detail.component.ts
  client/src/app/site/polls/components/poll-progress/poll-progress.component.html
  client/src/assets/styles/poll-colors.scss
  openslides/assignments/config_variables.py
  openslides/motions/config_variables.py
Labels: development

#5191 Add option to export motions with pagebreaks
  client/src/app/core/pdf-services/pdf-document.service.ts
  client/src/app/site/motions/modules/shared-motion/motion-export-dialog/motion-export-dialog.component.html
  client/src/app/site/motions/modules/shared-motion/motion-export-dialog/motion-export-dialog.component.ts
  client/src/app/site/motions/services/motion-pdf-catalog.service.ts
Labels: feature, motions, pdf

#5193 Allow final versions without change reco
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: feature, motions

#5197 Fixed some errors
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.ts
  openslides/agenda/apps.py
  openslides/assignments/apps.py
  openslides/assignments/models.py
  openslides/assignments/serializers.py
  openslides/motions/apps.py
  openslides/utils/access_permissions.py
  tests/integration/assignments/test_viewset.py
Labels: development

#5207 Number poll candidates depending on setting
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.html
Labels: development

#5209 Hide print-template button
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: client

#5190 Reworks the banner showing if there are polls
  client/src/app/core/ui-services/banner.service.ts
  client/src/app/core/ui-services/voting-banner.service.ts
  client/src/app/shared/components/banner/banner.component.html
  client/src/app/shared/components/banner/banner.component.scss
Labels: development

#5198 Adds a chart for assignment-poll-detail
  client/src/app/shared/components/charts/charts.component.html
  client/src/app/shared/components/charts/charts.component.scss
  client/src/app/shared/components/charts/charts.component.ts
  client/src/app/site/assignments/components/assignment-poll-detail/assignment-poll-detail.component.html
  client/src/app/site/assignments/components/assignment-poll-detail/assignment-poll-detail.component.scss
  client/src/app/site/assignments/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/polls/components/base-poll-detail.component.ts
Labels: development

#5208 Improved shared poll list
  client/src/app/site/assignments/models/view-assignment-poll.ts
  client/src/app/site/motions/models/view-motion-poll.ts
  client/src/app/site/polls/components/poll-list/poll-list.component.html
  client/src/app/site/polls/models/view-base-poll.ts
Labels: development

#5185 Adjust pollmethod votes
  client/src/app/site/assignments/components/assignment-poll-dialog/assignment-poll-dialog.component.html
  client/src/app/site/assignments/components/assignment-poll-vote/assignment-poll-vote.component.html
  client/src/app/site/assignments/components/assignment-poll-vote/assignment-poll-vote.component.ts
  client/src/app/site/polls/components/poll-form/poll-form.component.html
  client/src/app/site/polls/components/poll-form/poll-form.component.ts
  client/src/app/site/polls/models/view-base-poll.ts
  openslides/assignments/views.py
Labels: development

#5194 Fixes permissions for assignments
  client/src/app/shared/directives/perms.directive.ts
  client/src/app/shared/models/poll/base-poll.ts
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.html
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.scss
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.html
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.ts
Labels: development

#5199 Replaces the mat-table with a classic table
  client/src/app/shared/pipes/poll-key-verbose.pipe.spec.ts
  client/src/app/shared/pipes/poll-key-verbose.pipe.ts
  client/src/app/shared/shared.module.ts
  client/src/app/site/assignments/models/view-assignment-poll.ts
  client/src/app/site/motions/models/view-motion-poll.ts
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.scss-theme.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.scss
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.scss-theme.scss
  client/src/app/site/polls/models/view-base-poll.ts
  client/src/styles.scss
Labels: development
