Repository OpenSlides/OpenSlides, pull requests merged in 2020-05, with the labels that each got.

#5349 Set tinymce urls to absolute
  client/src/app/base.component.ts
Labels: bug, dependencies

#5321 Projector indicator list view tables
  client/src/app/shared/components/list-view-table/list-view-table.component.html
  client/src/app/shared/components/list-view-table/list-view-table.component.scss
  client/src/app/shared/components/list-view-table/list-view-table.component.scss-theme.scss
  client/src/app/shared/components/list-view-table/list-view-table.component.spec.ts
  client/src/app/shared/components/list-view-table/list-view-table.component.ts
  client/src/app/site/agenda/components/agenda-list/agenda-list.component.html
  client/src/app/site/agenda/components/agenda-list/agenda-list.component.scss
  client/src/app/site/motions/modules/motion-block/components/motion-block-detail/motion-block-detail.component.html
  client/src/app/site/motions/modules/motion-list/components/motion-list/motion-list.component.html
  client/src/assets/styles/tables.scss
  client/src/styles.scss
Labels: client, feature

#5351 Fix poll results under iOS
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.html
Labels: bug, dependencies

#5354 Fix unnecessary and unfunctional lock for production usage with gunicorn
  openslides/core/config.py
Labels: bug

#5347 Create statistics of closed list of speakers
  client/src/app/core/repositories/agenda/list-of-speakers-repository.service.ts
  client/src/app/core/ui-services/duration.service.ts
  client/src/app/shared/components/list-view-table/list-view-table.component.ts
  client/src/app/site/common/components/count-users/count-users.component.html
  client/src/app/site/common/components/legal-notice/legal-notice.component.html
  client/src/app/site/common/components/user-statistics/user-statistics.component.html
  client/src/app/site/common/components/user-statistics/user-statistics.component.scss
  client/src/app/site/common/components/user-statistics/user-statistics.component.scss-theme.scss
  client/src/app/site/common/components/user-statistics/user-statistics.component.spec.ts
  client/src/app/site/common/components/user-statistics/user-statistics.component.ts
  client/src/app/site/common/os-common.module.ts
  client/src/styles.scss
Labels: client

#5352 Manual cd for list of speakers
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.ts
Labels: bug, client

#5367 Hide the submitter-box in motion slide if empty
  client/src/app/slides/motions/motion/motion-slide-data.ts
  client/src/app/slides/motions/motion/motion-slide.component.html
  client/src/app/slides/motions/motion/motion-slide.component.ts
Labels: feature

#5366 Change motion cr mode view behavior
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: bug

#5359 Add permission as lookup object
  client/src/app/base.component.ts
  client/src/app/core/core-services/auth-guard.service.ts
  client/src/app/core/core-services/fallback-routes.service.ts
  client/src/app/core/core-services/main-menu.service.ts
  client/src/app/core/core-services/operator.service.ts
  client/src/app/core/repositories/users/group-repository.service.ts
  client/src/app/fullscreen-projector/fullscreen-projector/fullscreen-projector.component.ts
  client/src/app/shared/components/list-view-table/list-view-table.component.ts
  client/src/app/shared/directives/perms.directive.ts
  client/src/app/shared/models/motions/state.ts
  client/src/app/shared/models/users/group.ts
  client/src/app/site/agenda/agenda-routing.module.ts
  client/src/app/site/agenda/agenda.config.ts
  client/src/app/site/agenda/components/agenda-list/agenda-list.component.ts
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/assignments/assignments-routing.module.ts
  client/src/app/site/assignments/assignments.config.ts
  client/src/app/site/assignments/components/assignment-detail/assignment-detail.component.ts
  client/src/app/site/assignments/components/assignment-list/assignment-list.component.html
  client/src/app/site/assignments/components/assignment-list/assignment-list.component.ts
  client/src/app/site/assignments/components/assignment-poll-detail/assignment-poll-detail.component.ts
  client/src/app/site/common/common-routing.module.ts
  client/src/app/site/common/common.config.ts
  client/src/app/site/common/components/legal-notice/legal-notice.component.ts
  client/src/app/site/common/components/privacy-policy/privacy-policy.component.ts
  client/src/app/site/common/components/start/start.component.ts
  client/src/app/site/config/config.config.ts
  client/src/app/site/history/history.config.ts
  client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.ts
  client/src/app/site/mediafiles/mediafile.config.ts
  client/src/app/site/mediafiles/mediafiles-routing.module.ts
  client/src/app/site/motions/modules/category/components/category-detail/category-detail.component.ts
  client/src/app/site/motions/modules/category/components/category-list/category-list.component.ts
  client/src/app/site/motions/modules/motion-block/components/motion-block-detail/motion-block-detail.component.ts
  client/src/app/site/motions/modules/motion-block/components/motion-block-list/motion-block-list.component.ts
  client/src/app/site/motions/modules/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts
  client/src/app/site/motions/modules/motion-poll/motion-poll-detail/motion-poll-detail.component.ts
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.ts
  client/src/app/site/motions/modules/motion-workflow/components/workflow-detail/workflow-detail.component.ts
  client/src/app/site/motions/motions-routing.module.ts
  client/src/app/site/motions/motions.config.ts
  client/src/app/site/motions/services/local-permissions.service.ts
  client/src/app/site/motions/services/motion-filter-list.service.ts
  client/src/app/site/projector/components/projector-detail/projector-detail.component.ts
  client/src/app/site/projector/components/projector-list-entry/projector-list-entry.component.ts
  client/src/app/site/projector/components/projector-list/projector-list.component.ts
  client/src/app/site/projector/projector-routing.module.ts
  client/src/app/site/projector/projector.config.ts
  client/src/app/site/site-routing.module.ts
  client/src/app/site/topics/components/topic-detail/topic-detail.component.ts
  client/src/app/site/topics/topics-routing.module.ts
  client/src/app/site/users/components/group-list/group-list.component.ts
  client/src/app/site/users/components/password/password.component.ts
  client/src/app/site/users/components/presence-detail/presence-detail.component.ts
  client/src/app/site/users/components/user-detail/user-detail.component.ts
  client/src/app/site/users/components/user-list/user-list.component.ts
  client/src/app/site/users/models/view-group.ts
  client/src/app/site/users/users-routing.module.ts
  client/src/app/site/users/users.config.ts
Labels: clean up, client

#5372 Allow unset gender in user form
  client/src/app/site/users/components/user-detail/user-detail.component.html
Labels: bug

#5370 Add tags for agenda items
  client/src/app/core/repositories/agenda/item-repository.service.ts
  client/src/app/shared/models/agenda/item.ts
  client/src/app/site/agenda/components/agenda-list/agenda-list.component.html
  client/src/app/site/agenda/components/item-info-dialog/item-info-dialog.component.html
  client/src/app/site/agenda/components/item-info-dialog/item-info-dialog.component.ts
  client/src/app/site/agenda/models/view-item.ts
  client/src/app/site/agenda/services/agenda-csv-export.service.ts
  client/src/app/site/agenda/services/agenda-filter-list.service.ts
  openslides/agenda/migrations/0009_item_tags.py
  openslides/agenda/models.py
  openslides/agenda/serializers.py
  tests/integration/agenda/test_viewset.py
  tests/integration/motions/test_motions.py
Labels: agenda, feature

#5373 Show assignment poll result table instad of chart
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.html
  client/src/app/site/assignments/components/assignment-poll/assignment-poll.component.scss
Labels: client, feature, voting

#5380 Fix the CLOS service to trigger on CLOS updates
  client/src/app/core/core-services/projector.service.ts
  client/src/app/site/agenda/components/list-of-speakers/list-of-speakers.component.ts
  client/src/app/site/projector/components/presentation-control/presentation-control.component.ts
  client/src/app/site/projector/components/projector-detail/projector-detail.component.ts
  client/src/app/site/projector/services/current-agenda-item.service.ts
  client/src/app/site/projector/services/current-list-of-speakers-slide.service.ts
  client/src/app/site/projector/services/current-list-of-speakers.service.ts
  client/src/app/slides/services/slide-manager.service.ts
Labels: high
