Repository OpenSlides/OpenSlides, pull requests merged in 2021-11, with the labels that each got.

#6265 ClientIssue553: Add Testmailserver to openslides-dev-setup
  docker/docker-compose.dev.yml
Labels: OpenSlides4

#6270 BackendIssue1008 models.yml etc. moved to backend, remove omitted workflows
  .github/workflows/md5_check_initial-data.yml
  .github/workflows/models.yml
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
  docs/modelsvalidator/requirements.txt
  docs/modelsvalidator/setup.cfg
  docs/modelsvalidator/validate.py
  docs/permission.yml
Labels: OpenSlides4, meta

#6276 Makes the motion block detail and motion list more user friendly
  client/src/app/site/common/components/user-statistics/user-statistics.component.ts
  client/src/app/site/motions/modules/motion-block/components/motion-block-detail/motion-block-detail.component.ts
  client/src/app/site/motions/modules/motion-list/components/motion-list/motion-list.component.ts
  client/src/app/site/users/components/user-list/user-list.component.ts
Labels: client

#6281 Change the initial data
  docker/docker-compose.dev.yml
Labels: OpenSlides4

#6284 fix missing caddy_base when rebuilding
  proxy/entrypoint
Labels: OpenSlides4

#6290 add vote-service to build-images workflow
  .github/workflows/build_images.yml
Labels: OpenSlides4

#6291 Remove GHActions to announce file changes
  .github/announcement_templates/updates-to-initial-data.md
  .github/announcement_templates/updates-to-models.md
  .github/announcement_templates/updates-to-permissions.md
  .github/workflows/announce-initial-data-updates.yml
  .github/workflows/announce-model-updates.yml
  .github/workflows/announce-permission-updates.yml
Labels: documentation, meta

#6287 Fixes high amount of groups
  client/src/app/site/users/components/group-list/group-list.component.html
Labels: client, OpenSlides3

#6288 Add volumes to vote-dev-environment
  docker/docker-compose.dev.yml
Labels: feature, OpenSlides4

#6293 Run cypress workflow without docker
  .github/workflows/test-integration.yml
  integration/Dockerfile
  integration/cypress-docker.json
  integration/cypress.json
  integration/cypress/integration/committee-update.spec.js
  integration/entrypoint.sh
  integration/package-lock.json
  integration/package.json
  integration/resource-config-docker.js
  integration/resource-config.js
Labels: feature

#6296 Update exporter to newest backend
  server/openslides/core/export.py
Labels: OpenSlides3
