Repository OpenSlides/OpenSlides, pull requests merged in 2021-02, with the labels that each got.

#5811 Add applause in client
  client/package-lock.json
  client/package.json
  client/src/app/app.component.ts
  client/src/app/core/ui-services/applause.service.spec.ts
  client/src/app/core/ui-services/applause.service.ts
  client/src/app/shared/animations.ts
  client/src/app/shared/components/applause-display/applause-display.component.html
  client/src/app/shared/components/applause-display/applause-display.component.scss
  client/src/app/shared/components/applause-display/applause-display.component.spec.ts
  client/src/app/shared/components/applause-display/applause-display.component.ts
  client/src/app/shared/components/jitsi/jitsi.component.html
  client/src/app/shared/components/jitsi/jitsi.component.scss
  client/src/app/shared/components/jitsi/jitsi.component.scss-theme.scss
  client/src/app/shared/components/jitsi/jitsi.component.ts
  client/src/app/shared/components/particle-display/particle-display.component.html
  client/src/app/shared/components/particle-display/particle-display.component.scss
  client/src/app/shared/components/particle-display/particle-display.component.spec.ts
  client/src/app/shared/components/particle-display/particle-display.component.ts
  client/src/app/shared/components/progress/progress.component.html
  client/src/app/shared/components/progress/progress.component.scss
  client/src/app/shared/components/progress/progress.component.scss-theme.scss
  client/src/app/shared/components/progress/progress.component.spec.ts
  client/src/app/shared/components/progress/progress.component.ts
  client/src/app/shared/components/vjs-player/vjs-player.component.html
  client/src/app/shared/components/vjs-player/vjs-player.component.scss
  client/src/app/shared/components/vjs-player/vjs-player.component.ts
  client/src/app/shared/directives/resized.directive.ts
  client/src/app/shared/shared.module.ts
  client/src/app/site/common/components/start/start.component.html
  client/src/assets/styles/component-themes.scss
  client/src/assets/styles/themes/default-dark.scss
  client/src/assets/styles/themes/default-light.scss
  client/src/assets/styles/themes/green-dark.scss
  client/src/assets/styles/themes/green-light.scss
  client/src/assets/styles/themes/red-dark.scss
  client/src/assets/styles/themes/red-light.scss
  client/src/assets/styles/themes/solarized-dark.scss
  client/src/assets/svg/clapping_hands.svg
  client/src/styles.scss
  server/docker/Dockerfile.dev
  server/openslides/core/config_variables.py
Labels: client, feature, high

#5836 Added permissions to models.yml
  docs/models.yml
Labels: OpenSlides4, backend, client, permission

#5843 Fix action interface
  docs/interfaces/action-service.txt
Labels: OpenSlides4, meta

#5841 Cleanup some applause code
  client/src/app/core/ui-services/applause.service.ts
  client/src/app/shared/components/applause-bar-display/applause-bar-display.component.html
  client/src/app/shared/components/applause-bar-display/applause-bar-display.component.scss
  client/src/app/shared/components/applause-bar-display/applause-bar-display.component.spec.ts
  client/src/app/shared/components/applause-bar-display/applause-bar-display.component.ts
  client/src/app/shared/components/applause-particle-display/applause-particle-display.component.html
  client/src/app/shared/components/applause-particle-display/applause-particle-display.component.scss
  client/src/app/shared/components/applause-particle-display/applause-particle-display.component.spec.ts
  client/src/app/shared/components/applause-particle-display/applause-particle-display.component.ts
  client/src/app/shared/components/applause-particle-display/particle-options.ts
  client/src/app/shared/components/jitsi/jitsi.component.html
  client/src/app/shared/components/particle-display/particle-display.component.html
  client/src/app/shared/components/particle-display/particle-display.component.ts
  client/src/app/shared/components/vjs-player/vjs-player.component.html
  client/src/app/shared/directives/resized.directive.ts
  client/src/app/shared/shared.module.ts
Labels: clean up, client

#5844 Revert "Fix action interface"
  docs/interfaces/action-service.txt
Labels: OpenSlides4

#5832 Add helpdesk icon and feature
  client/src/app/shared/components/jitsi/jitsi.component.html
  client/src/app/shared/components/jitsi/jitsi.component.ts
  server/openslides/core/config_variables.py
Labels: client, feature

#5848 Adjust datastore interface
  docs/interfaces/datastore-service.txt
Labels: OpenSlides4, datastore, documentation

#5831 Fix initial data
  docker/initial-data.json
Labels: OpenSlides4, meta

#5823 Fix csv importing users with groups
  client/src/app/site/users/components/user-import/user-import-list.component.html
  client/src/app/site/users/components/user-import/user-import-list.component.scss
  client/src/app/site/users/components/user-import/user-import-list.component.ts
  client/src/app/site/users/models/import-create-user.ts
  client/src/app/site/users/services/user-import.service.ts
Labels: bug, client, high

#5855 Added permission.yml.
  docs/permission.yml
Labels: OpenSlides4

#5770 Support youtube as livestream URL
  client/src/app/shared/components/jitsi/jitsi.component.html
  client/src/app/shared/components/jitsi/jitsi.component.ts
  client/src/app/shared/components/live-stream/live-stream.component.html
  client/src/app/shared/components/live-stream/live-stream.component.scss
  client/src/app/shared/components/live-stream/live-stream.component.ts
  client/src/app/shared/components/video-player/video-player.component.html
  client/src/app/shared/components/video-player/video-player.component.scss
  client/src/app/shared/components/video-player/video-player.component.spec.ts
  client/src/app/shared/components/video-player/video-player.component.ts
  client/src/app/shared/components/vjs-player/vjs-player.component.html
  client/src/app/shared/components/vjs-player/vjs-player.component.spec.ts
  client/src/app/shared/components/vjs-player/vjs-player.component.ts
  client/src/app/shared/shared.module.ts
Labels: feature, high

#5880 Map debug port for openslides-backend in docker-compose.dev
  docker/docker-compose.dev.yml
Labels: OpenSlides4, meta

#5858 Fixed modelsvalidator.
  docs/modelsvalidator/check/check.go
  docs/modelsvalidator/check/check_test.go
Labels: OpenSlides4, meta

#5888 Fix paragraph based amendments in iOS
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.html
Labels: bug, dependencies

#5896 More change detection in jitsi bar
  client/src/app/shared/components/jitsi/jitsi.component.ts
Labels: bug, client, high

#5897 Fixes an infinite running spinner
  client/src/app/app.component.spec.ts
  client/src/app/app.component.ts
  client/src/app/app.module.ts
  client/src/app/core/core-services/http-interceptors/index.ts
  client/src/app/core/core-services/http-interceptors/noop-interceptor.service.spec.ts
  client/src/app/core/core-services/http-interceptors/noop-interceptor.service.ts
  client/src/app/core/core-services/openslides.service.ts
  client/src/app/core/core-services/stable.service.spec.ts
  client/src/app/core/core-services/stable.service.ts
  client/src/app/site/projector/components/projector-detail/projector-detail.component.ts
  client/src/app/site/projector/components/projector-list/projector-list.component.ts
Labels: client

#5900 Remodel the projector
  docker/initial-data.json
  docs/datavalidator/check_json.py
  docs/example-data.json
  docs/models.yml
  docs/modelsvalidator/check/check.go
Labels: OpenSlides4

#5914 Add 'minimum' for some fields in Projector
  docs/models.yml
Labels: OpenSlides4

#5906 Fix action interface
  docs/interfaces/action-service.txt
Labels: backend, documentation

#5907 Add replacement to structured fields
  docs/models.yml
Labels: OpenSlides4, backend
