Repository OpenSlides/OpenSlides, pull requests merged in 2021-07, with the labels that each got.

#6141 Fix initial data for conference_auto_connect_next_speakers and datavalidator for number fields
  docker/initial-data.json
  docs/datavalidator/check_json.py
  docs/example-data.json
Labels: OpenSlides4, meta

#6142 Add conference_enable_helpdesk to models
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4

#6145 Split forwarding_tree_motion_ids into two fields
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4, meta

#6153 Adds applause configs to the meeting model
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4

#6155 Remove majority method
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4

#6162 Add cascade deletion to user->speaker relation
  docs/models.yml
Labels: OpenSlides4

#6165 Update dockerfiles for node 16 and a12
  client/docker/Dockerfile
  client/docker/Dockerfile.dev
Labels: bug, client, dependencies

#6168 Fix limits for LOS settings (closes #6167)
  docs/models.yml
Labels: OpenSlides4, meta

#6171 Hide pw generate button while editing a user
  client/src/app/site/users/components/user-detail/user-detail.component.html
Labels: client

#6172 Fix missing zip extension when filename had a dot
  client/src/app/core/repositories/mediafiles/mediafile-repository.service.ts
  client/src/app/site/mediafiles/components/mediafile-list/mediafile-list.component.ts
Labels: bug, client

#6173 Add rdquo und Prime to special diff entities
  client/src/app/core/ui-services/diff.service.ts
Labels: bug, client

#6176 Scrollable sorted jitsi user list
  client/src/app/site/interaction/components/call/call.component.html
  client/src/app/site/interaction/components/call/call.component.scss
  client/src/app/site/interaction/components/call/call.component.ts
  client/src/app/site/interaction/services/rtc.service.ts
Labels: bug, client

#6177 Hide chat in jitsi iFrame
  client/src/app/site/interaction/services/rtc.service.ts
Labels: client, feature

#6182 Dev model gender
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: backend

#6185 Fix an error where the workflow would break agenda
  client/src/app/core/core-services/projector.service.ts
Labels: bug, client, meta

#6184 Fix mat-table no flex class
  client/src/app/site/motions/modules/category/components/category-detail/category-detail.component.html
  client/src/app/site/motions/modules/motion-import/motion-import-list.component.html
  client/src/app/site/motions/modules/statute-paragraph/components/statute-import-list/statute-import-list.component.html
  client/src/app/site/topics/components/topic-import-list/topic-import-list.component.html
  client/src/app/site/users/components/group-list/group-list.component.html
  client/src/app/site/users/components/group-list/group-list.component.scss
Labels: bug, dependencies, high, meta

#6187 Fix default motion preamble
  docs/models.yml
Labels: OpenSlides4

#6186 Add CSV import for supporters
  client/src/app/site/motions/models/import-create-motion.ts
  client/src/app/site/motions/modules/motion-import/motion-import-list.component.html
  client/src/app/site/motions/services/motion-csv-export.service.ts
  client/src/app/site/motions/services/motion-import.service.ts
  client/src/styles.scss
Labels: client, feature

#6189 motion_submitter does not need a default. In the creating a weight is…
  docs/models.yml
Labels: backend
