Repository OpenSlides/OpenSlides, pull requests merged in 2021-06, with the labels that each got.

#6086 Fix non existing top nav for motions
  client/src/app/site/motions/modules/motion-detail/components/motion-detail/motion-detail.component.ts
Labels: bug

#5961 Restructure communication components
  client/src/app/core/ui-services/diff.service.ts
  client/src/app/shared/animations.ts
  client/src/app/shared/components/jitsi/jitsi.component.html
  client/src/app/shared/components/jitsi/jitsi.component.scss
  client/src/app/shared/components/jitsi/jitsi.component.scss-theme.scss
  client/src/app/shared/components/jitsi/jitsi.component.ts
  client/src/app/shared/components/progress/progress.component.ts
  client/src/app/shared/components/video-player/video-player.component.html
  client/src/app/shared/components/video-player/video-player.component.scss
  client/src/app/shared/components/video-player/video-player.component.ts
  client/src/app/shared/shared.module.ts
  client/src/app/site/interaction/components/action-bar/action-bar.component.html
  client/src/app/site/interaction/components/action-bar/action-bar.component.scss
  client/src/app/site/interaction/components/action-bar/action-bar.component.spec.ts
  client/src/app/site/interaction/components/action-bar/action-bar.component.ts
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.html
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.scss
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.spec.ts
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.ts
  client/src/app/site/interaction/components/applause-particle-display/applause-particle-display.component.html
  client/src/app/site/interaction/components/applause-particle-display/applause-particle-display.component.scss
  client/src/app/site/interaction/components/applause-particle-display/applause-particle-display.component.spec.ts
  client/src/app/site/interaction/components/applause-particle-display/applause-particle-display.component.ts
  client/src/app/site/interaction/components/applause-particle-display/particle-options.ts
  client/src/app/site/interaction/components/call-dialog/call-dialog.component.html
  client/src/app/site/interaction/components/call-dialog/call-dialog.component.scss
  client/src/app/site/interaction/components/call-dialog/call-dialog.component.spec.ts
  client/src/app/site/interaction/components/call-dialog/call-dialog.component.ts
  client/src/app/site/interaction/components/call/call.component.html
  client/src/app/site/interaction/components/call/call.component.scss
  client/src/app/site/interaction/components/call/call.component.spec.ts
  client/src/app/site/interaction/components/call/call.component.ts
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.html
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.scss
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.spec.ts
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.ts
  client/src/app/site/interaction/components/stream/stream.component.html
  client/src/app/site/interaction/components/stream/stream.component.scss
  client/src/app/site/interaction/components/stream/stream.component.spec.ts
  client/src/app/site/interaction/components/stream/stream.component.ts
  client/src/app/site/interaction/interaction.module.ts
  client/src/app/site/interaction/services/applause.service.spec.ts
  client/src/app/site/interaction/services/applause.service.ts
  client/src/app/site/interaction/services/call-restriction.service.spec.ts
  client/src/app/site/interaction/services/call-restriction.service.ts
  client/src/app/site/interaction/services/interaction.service.spec.ts
  client/src/app/site/interaction/services/interaction.service.ts
  client/src/app/site/interaction/services/rtc.service.spec.ts
  client/src/app/site/interaction/services/rtc.service.ts
  client/src/app/site/interaction/services/stream.service.spec.ts
  client/src/app/site/interaction/services/stream.service.ts
  client/src/app/site/interaction/services/user-media-perm.service.spec.ts
  client/src/app/site/interaction/services/user-media-perm.service.ts
  client/src/app/site/site.component.html
  client/src/app/site/site.component.scss
  client/src/app/site/site.module.ts
  client/src/assets/styles/component-themes.scss
  client/src/assets/styles/global-components-style.scss
  server/openslides/core/config_variables.py
Labels: clean up, client, heavy, high

#6093 is_demo_user is no more read only
  docs/models.yml
Labels: OpenSlides4, meta

#6102 Hide conference bar without interaction
  client/src/app/site/interaction/components/call/call.component.html
  client/src/app/site/interaction/components/call/call.component.ts
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.ts
  client/src/app/site/interaction/services/call-restriction.service.ts
  client/src/app/site/interaction/services/interaction.service.ts
  client/src/app/site/interaction/services/stream.service.ts
Labels: client

#6100 Add pending state for chat message
  client/src/app/site/chat/components/chat-tabs/chat-tabs.component.html
  client/src/app/site/chat/components/chat-tabs/chat-tabs.component.ts
Labels: client, feature

#6103 Update jitsi iFrame and API
  client/src/app/site/interaction/services/rtc.service.ts
  client/src/assets/jitsi/external_api.js
Labels: client, feature

#6106 Fix some icon error in contra speech
  client/src/app/shared/components/list-of-speakers-content/list-of-speakers-content.component.html
Labels: bug

#6105 Limit pushing of filter updates in filter service
  client/src/app/core/ui-services/base-filter-list.service.ts
Labels: bug, client

#6110 Set change detection in cinema to default
  client/src/app/site/cinema/components/cinema/cinema.component.ts
Labels: client

#6112 Remove CD from Cinema completely
  client/src/app/site/cinema/components/cinema/cinema.component.ts
Labels: bug, high

#6115 Update datastore interface for model locked error
  docs/interfaces/datastore-service.txt
Labels: OpenSlides4, datastore

#6116 Move custom_translation from organization to meeting
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4

#6124 Enhance datavalidator for template fields
  docker/initial-data.json
  docs/datavalidator/check_json.py
  docs/example-data.json
Labels: OpenSlides4, meta

#6125 Add imported_at to models.yml
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: documentation

#6127 Use vote pending state as subject
  client/src/app/site/assignments/modules/assignment-poll/components/assignment-poll/assignment-poll.component.html
  client/src/app/site/motions/modules/motion-poll/motion-poll/motion-poll.component.html
  client/src/app/site/polls/components/base-poll.component.ts
Labels: bug, client

#6128 Adjust datavalidator
  docs/datavalidator/check_json.py
Labels: OpenSlides4, meta

#6129 Fix firefox endless spinner in stream
  client/src/app/site/interaction/components/applause-particle-display/applause-particle-display.component.html
  client/src/app/site/interaction/components/applause-particle-display/applause-particle-display.component.ts
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.scss
Labels: bug, high

#6121 Move applause timeout to service
  client/src/app/site/interaction/components/action-bar/action-bar.component.html
  client/src/app/site/interaction/components/action-bar/action-bar.component.ts
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.html
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.scss
  client/src/app/site/interaction/components/applause-bar-display/applause-bar-display.component.ts
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.ts
  client/src/app/site/interaction/services/applause.service.ts
Labels: bug

#6133 Fix exporting the DS
  docker/docker-compose.dev.yml
Labels: OpenSlides4, meta
