Repository OpenSlides/OpenSlides, pull requests merged in 2021-04, with the labels that each got.

#5993 Adapt models.yml to new voting changes
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4, meta

#6000 Add organisation tags
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4, meta

#5997 Prevent multiple entries in entitled_users_at_stop
  server/openslides/assignments/migrations/0024_assignmentpoll_entitled_users_remove_duplicates.py
  server/openslides/motions/migrations/0043_motionpoll_entitled_users_remove_duplicates.py
  server/openslides/poll/migrations/poll_migration_helper.py
  server/openslides/poll/models.py
  server/tests/integration/motions/test_polls.py
Labels: bug

#6001 Recommendation extension can be set with can_manage_metadata
  server/openslides/motions/views.py
  server/tests/integration/motions/test_motions.py
Labels: OpenSlides4

#6011 Issue473 meeting.reference projector id and user.username required
  docs/models.yml
Labels: OpenSlides4, backend

#6012 Make countdown times required
  docs/models.yml
Labels: OpenSlides4, meta

#6006 Lock poll to prevent race conditions
  server/openslides/assignments/migrations/0025_assignmentpoll_fix_vote_values.py
  server/openslides/motions/migrations/0044_motionpoll_fix_vote_values.py
  server/openslides/poll/migrations/poll_migration_helper.py
  server/openslides/poll/views.py
Labels: bug

#6018 Change locked fields to a list
  docs/interfaces/datastore-service.txt
Labels: OpenSlides4, datastore, meta

#6024 Fix vote delegation update error
  docker/docker-compose.dev.yml
  server/openslides/users/views.py
  server/tests/integration/users/test_viewset.py
Labels: bug, high

#6041 Pro/contra/marked/note for OS4
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4, meta

#6040 Find umlauts using search
  client/src/app/app.component.ts
  client/src/app/site/motions/models/view-motion.ts
  client/src/app/site/topics/models/view-topic.ts
Labels: bug, client

#6031 Fix entitled user calculation and display of voting banner in case of vote delegations
  client/src/app/core/ui-services/voting-banner.service.ts
  server/openslides/poll/models.py
  server/tests/integration/motions/test_polls.py
Labels: bug
