Repository OpenSlides/OpenSlides, pull requests merged in 2021-08, with the labels that each got.

#6192 Add field group info in organization
  docs/datavalidator/check_json.py
  docs/models.yml
Labels: OpenSlides4, high, meta

#6194 Add missing defaults & fix existing ones
  docs/models.yml
Labels: OpenSlides4

#6152 Moved production setup to manage service.
  README.md
  docker/docker-compose.yml.m4
  docker/docker-stack.yml.m4
  docker/initial-data.json
  docker/setup-prod.sh
Labels: OpenSlides4

#6202 Show Helpdesk without live streams
  client/src/app/site/interaction/components/action-bar/action-bar.component.html
  client/src/app/site/interaction/components/action-bar/action-bar.component.ts
  client/src/app/site/interaction/components/interaction-container/interaction-container.component.ts
Labels: meta, client

#6206 github models.yml: generate models.py for backend check_json
  .github/workflows/models.yml
Labels: OpenSlides4, meta

#6208 Monitor and announces changes to models and perms
  .github/announcement_templates/updates-to-models.md
  .github/announcement_templates/updates-to-permissions.md
  .github/workflows/announce-model-updates.yml
  .github/workflows/announce-permission-updates.yml
Labels: documentation, OpenSlides4, meta

#6211 Update readme
  .github/workflows/md5_check_initial-data.yml
  DEVELOPMENT.md
  README.md
Labels: documentation, OpenSlides4

#6212 Clean HTML before pasting in tinymce
  client/src/app/base.component.ts
Labels: feature, high, client
