Repository OpenSlides/OpenSlides, pull requests merged in 2021-01, with the labels that each got.

#5794 Docs in model.yml
  docs/models.yml
Labels: OpenSlides4

#5800 Fix vote_delegated_from_user_ids on user update
  server/openslides/users/views.py
  server/tests/integration/users/test_viewset.py
Labels: bug, high

#5803 Update initial data
  docker/initial-data.json
Labels: OpenSlides4

#5723 Change the category prefix to optional
  docs/models.yml
Labels: OpenSlides4

#5768 Update Datastore interface
  docs/interfaces/datastore-service.txt
Labels: OpenSlides4

#5783 Add config defaults to models.yml settings.
  docs/models.yml
Labels: OpenSlides4

#5704 Update datastore specs
  docs/interfaces/datastore-service.txt
Labels: OpenSlides4

#5815 server: Fix database config in Docker entrypoint
  server/docker/entrypoint-db-setup
Labels: docker
