Repository OpenSlides/OpenSlides, pull requests merged in 2021-03, with the labels that each got.

#5898 Some cleanup in favor of spinner-fixes
  client/src/app/app.component.spec.ts
  client/src/app/app.component.ts
  client/src/app/core/core-services/http-interceptors/index.ts
  client/src/app/core/core-services/http-interceptors/noop-interceptor.service.spec.ts
  client/src/app/core/core-services/http-interceptors/noop-interceptor.service.ts
  client/src/app/core/core-services/http-interceptors/stable-interceptor.service.ts
  client/src/app/core/core-services/openslides-status.service.ts
  client/src/app/core/core-services/openslides.service.ts
  client/src/app/core/core-services/stable.service.spec.ts
  client/src/app/core/core-services/stable.service.ts
  client/src/app/site/projector/components/projector-detail/projector-detail.component.ts
  client/src/app/site/projector/components/projector-list/projector-list.component.ts
Labels: clean up

#5934 mediafile fields list_of_speakers_id and filename not required
  docs/models.yml
Labels: OpenSlides4, meta

#5942 Add defaults for closed on agenda item and list of speakers
  docs/models.yml
Labels: OpenSlides4, meta

#5917 Update projector_countdown
  docs/datavalidator/check_json.py
  docs/models.yml
Labels: OpenSlides4

#5947 N as new 100% base
  docs/models.yml
Labels: meta

#5949 List of speaker initially closed
  docker/initial-data.json
  docs/example-data.json
  docs/models.yml
Labels: OpenSlides4, meta

#5960 Change poll global default to false.
  docs/models.yml
Labels: OpenSlides4, backend

#5963 Make css_class required
  docs/models.yml
Labels: OpenSlides4, meta

#5973 Update poll onehundred_percent_base and majority_method defaults.
  docs/models.yml
Labels: backend

#5747 Update auth-service's interface
  docs/interfaces/auth-service.txt
Labels: OpenSlides4, clean up, documentation

#5979 Disable general no/yes depending on poll method
  client/src/app/site/polls/components/poll-form/poll-form.component.ts
Labels: clean up, client, high
