Repository OpenSlides/OpenSlides, pull requests merged in 2022-01, with the labels that each got.

#6318 Fixes percentbase of candidates in assignments
  client/src/app/shared/components/assignment-poll-detail-content/assignment-poll-detail-content.component.html
  client/src/app/shared/pipes/poll-percent-base.pipe.ts
  client/src/app/site/assignments/modules/assignment-poll/services/assignment-poll.service.ts
  client/src/app/site/assignments/services/assignment-pdf.service.ts
  client/src/app/site/motions/services/motion-pdf.service.ts
  client/src/app/site/polls/services/poll.service.ts
  server/requirements/development.txt
Labels: OpenSlides3

#6325 Set various information to "main"
  DEVELOPMENT.md
  Makefile
  docker/docker-compose.dev.yml
  proxy/Dockerfile
  services-to-main.sh
Labels: clean up

#6327 Fix various exporter issues
  server/openslides/core/export.py
Labels: bug, high
