Repository OpenSlides/OpenSlides, pull requests merged in 2022-02, with the labels that each got.

#6347 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: OpenSlides4

#6359 Dependency resolve
  README.rst
  server/requirements/development.txt
Labels: documentation, dependencies

#6350 Documentation improvements
  DEVELOPMENT.md
Labels: documentation

#6361 documentation overhaul (#6353)
  README.rst
Labels: documentation

#6362 Speed up the 'make run-dev' command
  Makefile
  dev-commands/submodules-do.sh
  services-to-main.sh
Labels: OpenSlides4, meta

#6372 simplify services-to-main.sh
  services-to-main.sh
Labels: clean up, OpenSlides4
