Repository OpenSlides/OpenSlides, pull requests merged in 2023-11, with the labels that each got.

#6669 Update labels and milestones script
  .github/meta/update_labels_and_milestones.py
Labels: enhancement

#6647 Add project automation
  .github/workflows/project-automation.yml
  .github/workflows/project-issue-closed.yml
  .github/workflows/project-pull-request-closed.yml
  .github/workflows/project-pull-request-opened.yml
  .github/workflows/project-pull-request-review-requested.yml
Labels: enhancement

#6675 build.sh: remove "built" from version string
  dev/docker/build.sh
Labels: clean up

#6692 Add `SECURITY.md`
  SECURITY.md
Labels: documentation

#6691 Remove `SYSTEM_URL` from `INSTALL.md`
  INSTALL.md
Labels: documentation, clean up

#6698 Add co-branch script
  dev/scripts/co-branch.sh
Labels: enhancement
