Repository OpenSlides/OpenSlides, pull requests merged in 2023-12, with the labels that each got.

#6702 Update translations and script
  dev/scripts/extract-translations.sh
  i18n/de.po
  i18n/template-en.pot
Labels: clean up

#6705 Update labels and milestones script
  .github/meta/requirements.txt
  dev/scripts/requirements.txt
  dev/scripts/update_labels_and_milestones.py
Labels: enhancement

#6710 Staging update 20231213
  VERSION
Labels: staging update

#6712 Add `openslides-proxy` to labels script
  dev/scripts/update_labels_and_milestones.py
Labels: enhancement

#6713 gh-action: Retag latest instead of building twice
  .github/workflows/build-images.yml
Labels: enhancement
