Repository OpenSlides/OpenSlides, pull requests merged in 2023-01, with the labels that each got.

#6495 Add backend setup
  DEVELOPMENT.md
  Makefile
  docker/docker-compose.dev.yml
  docker/docker-compose.test.yml
  docker/services.env
Labels: feature, high

#6534 Fix backend setup
  Makefile
  docker/docker-compose.backend.yml
Labels: bug

#6535 Add script to automatically set labels and milestones
  .github/meta/requirements.txt
  .github/meta/update_labels_and_milestones.py
Labels: feature

#6542 Add search service to labels script
  .github/meta/update_labels_and_milestones.py
Labels: enhancement

#6533 Changed INSTALL.md
  INSTALL.md
Labels: documentation

#6537 Restructure & clean up
  DEVELOPMENT.md
  Makefile
  db.sh
  dc-dev.sh
  dev-commands/README.md
  dev-commands/manage.sh
  dev/docker/build.sh
  dev/docker/dc.otel.dev.yml
  dev/docker/docker-compose.backend.yml
  dev/docker/docker-compose.dev.yml
  dev/docker/docker-compose.test.yml
  dev/docker/otel-collector-config.yml
  dev/docker/services.env
  dev/localprod/.gitignore
  dev/localprod/README.md
  dev/localprod/config.yml
  dev/localprod/setup.sh
  dev/scripts/README.md
  dev/scripts/clear-ds.sh
  dev/scripts/db.sh
  dev/scripts/dc-dev.sh
  dev/scripts/export-ds.sh
  dev/scripts/reset-db-import-sql.sh
  dev/scripts/services-to-main.sh
  dev/scripts/set-ds.sh
  dev/scripts/strip-meta-fields.py
  dev/scripts/submodules-do.sh
  docker/.env
  docker/reset-admin-password.sh
  docker/secrets/admin.env.example
  docker/secrets/user.env.example
  logo/README.rst
Labels: clean up, enhancement

#6543 Update INSTALL.md
  INSTALL.md
Labels: documentation

#6547 Adjust changed path for docker/build.sh script
  dev/docker/build.sh
Labels: clean up
