Repository OpenSlides/OpenSlides, pull requests merged in 2024-06, with the labels that each got.

#6783 Fix cli import_events
  dev/scripts/reset-db-import-sql.sh
Labels: bug

#6788 Add staging_log script
  Makefile
  dev/scripts/staging_log.sh
Labels: feature

#6762 Improve `README.md`
  README.md
Labels: documentation
