Repository OpenSlides/OpenSlides, pull requests merged in 2024-04, with the labels that each got.

#6770 Update docs and scripts to new docker compose syntax
  DEVELOPMENT.md
  INSTALL.md
  Makefile
  dev/localprod/README.md
  dev/scripts/README.md
  dev/scripts/db.sh
  dev/scripts/dc-dev.sh
  dev/scripts/set-ds.sh
Labels: documentation, clean up, waiting

#6775 Fix `ds-set.sh` for arbitrary large files
  dev/scripts/set-ds.sh
Labels: enhancement

#6777 Fix & cleanup scripts
  .github/workflows/test-integration.yml
  dev/scripts/export-ds.sh
  dev/scripts/set-ds.sh
Labels: bug, clean up
