Repository OpenSlides/OpenSlides, pull requests merged in 2024-02, with the labels that each got.

#6727 Add meta repo to script
  dev/scripts/update_labels_and_milestones.py
Labels: enhancement

#6728 add `make-update hotfix` workflow
  Makefile
  dev/scripts/make-update.sh
Labels: enhancement, waiting

#6725 build.sh: Set VERSION as build-arg for services
  dev/docker/build.sh
Labels: enhancement

#6733 Add compatibility and checks for meta repo
  dev/scripts/make-update.sh
Labels: meta

#6737 make services-to-main: Update meta-submodules after checkout service
  dev/scripts/make-update.sh
Labels: meta
